name: 🔁 Update DrewLive EPG 📺

on:
  schedule:
    - cron: '0,30 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-epg:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🐍 Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: 🎯 Run DrewLive EPG merger
        run: python drewepg.py

      - name: 💾 Commit & Push if EPG Changed
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # --- MATCHES YOUR SCRIPT OUTPUT ---
          git add DrewLive.xml.gz

          if git diff --cached --quiet; then
            echo "✅ No changes detected — skipping commit."
            exit 0
          fi

          git commit -m "🔁 Auto-update DrewLive EPG ($(date -u +'%Y-%m-%d %H:%M UTC'))"

          # Random delay to avoid push collisions
          sleep $((RANDOM % 10 + 5))

          if ! git push origin main; then
            echo "⚠️ Push failed, attempting safe rebase..."
            git pull origin main --rebase || {
              echo "❌ Rebase failed. Stopping to avoid corruption."
              exit 1
            }
            git push origin main || {
              echo "❌ Push failed again after rebase."
              exit 1
            }
          fi
